spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: username
    password: password
    driverClassName: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mail:
insourcing:
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password:password
    smtp_auth: true
    smtp_starttls_enable: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: username
    password: password
    driverClassName: oracle.jdbc.driver.OracleDriver
  proxy:
    host: host
    port: port
    username: username
    password: password
  scan:
    def_tgt1: 1FAX
    def_tgt2: 2FAX
    path1: D:\\pleiades\\fax\\
    path2: D:\\pleiades\\fax\\
  ocr:
    upload_path: D:\\pleiades\\upload\\
    input_path: D:\\pleiades\\input\\
    output_path: D:\\pleiades\\output\\
    host_url: host_url
    add_page: add_page
    add_sort: add_sort
    read_unit: read_unit
    read_sort: read_sort
    unit_export: unit_export
    link_entry: link_entry
    api_key: api_key
    api_key_value: api_key_value
    user_id: user_id

# SQLログ出力
logging:
  level:
    org:
      springframework: warn
    com:
      example:
        demo:
          UserDataMapper: debug
